
satellite :
    rx :
        antenna :
            #gain :
            #   - 'Gaussian'
            #   - 0
            aperture :
                - 'Gaussian'
                - 0                
            aperture_efficiency :
                - 'Gaussian'
                - 0
            polarization :
                - 'NotValid'
            pattern :
                - 'Gaussian'
                - 0
            noise_temp :
                - 'Gaussian'
                - 0
            tracking :
                - 'NotValid'
            pointing_loss :
                - 'Gaussian'
                - 0            
        cable :
            gain :
                - 'Gaussian'
                - 0
            noise_figure :
                - 'Gaussian'
                - 0
        lna :
            gain :
                - 'Gaussian'
                - 0
            noise_figure :
                - 'Gaussian'
                - 0
        filter :
            gain :
                - 'Gaussian'
                - 0
            noise_figure :
                - 'Gaussian'
                - 0
        demodulator :
            gain :
                - 'Gaussian'
                - 0
            noise_figure :
                - 'Gaussian'
                - 0
        receiver :
            implementation_loss :
                - 'Gaussian'
                - 0
    tx :
        antenna :
            #gain :
            #   - 'Gaussian'
            #   - 0
            aperture :
                - 'Gaussian'
                - 0
            aperture_efficiency :
                - 'Gaussian'
                - 0
            polarization :
                - 'NotValid
            pattern :
                - 'Gaussian'
                - 0
            tracking :
                - 'NotValid
            pointing_loss :
                - 'Gaussian'
                - 0
        pa :
            power :
                - 'Gaussian'
                - 0
            
ground_station :
    rx :
        antenna :
            #gain :
            #  - 'Gaussian'
            #   - 0
            aperture :
                - 'Gaussian'
                - 0
            aperture_efficiency :
                - 'Gaussian'
                - 0
            polarization :
                - 'NotValid
            pattern :
                - 'Gaussian'
                - 0
            noise_temp :
                - 'Gaussian'
                - 0
            tracking :
                - 'NotValid'
            pointing_loss :
                - 'Gaussian'
                - 0
        cable :
            gain :
                - 'Gaussian'
                - 0
            noise_figure :
                - 'Gaussian'
                - 0
        lna :
            gain :
                - 'Gaussian'
                - 0
            noise_figure :
                - 'Gaussian'
                - 0
        filter :
            gain :
                - 'Gaussian'
                - 0
            noise_figure :
                - 'Gaussian'
                - 0
        demodulator :
            gain :
                - 'Gaussian'
                - 0
            noise_figure :
                - 'Gaussian'
                - 0
        
    tx :
        antenna :
            #gain :
            #    - 'Gaussian'
            #    - 0
            aperture :
                - 'Gaussian'
                - 0
            aperture_efficiency :
                - 'Gaussian'
                - 0
            polarization :
                - 'NotValid'
            pattern :
                - 'Gaussian'
                - 0
            tracking :
                - 'NotValid'
            pointing_loss :
                - 'Gaussian'
                - 0
        pa :
            power :
                - 'Gaussian'
                - 0
            
downlink_channel :
    name                        :
        - 'NotValid'
    bitrate                     :
        - 'Fixed'
    allocation                  :
        - 'Fixed'
    center_freq                 :
        - 'Fixed'    
    atmospheric_loss            :
        - 'Gaussian'
        - 0
    ionospheric_loss            :
        - 'Gaussian'
        - 0
    rain_loss                   :
        - 'Gaussian'
        - 0
    multipath_fading            :
        - 'Gaussian'
        - 0
    polarization_mismatch_loss  :
        - 'Gaussian'
        - 0
    
uplink_channel :
    name                        :
        - 'NotValid'
    bitrate                     :
        - 'Fixed'
    allocation                  :
        - 'Fixed'
    center_freq                 :
        - 'Fixed'
    atmospheric_loss            :
        - 'Gaussian'
        - 0
    ionospheric_loss            :
        - 'Gaussian'
        - 0
    rain_loss                   :
        - 'Gaussian'
        - 0
    multipath_fading            :
        - 'Gaussian'
        - 0
    polarization_mismatch_loss  :
        - 'Gaussian'
        - 0

geometry :
    apoapsis_altitude           :
        - 'Fixed'
    periapsis_altitude          :
        - 'Fixed'
    min_elevation               :
        - 'Fixed'