
satellite :
    rx :
        antenna :
            #gain                : 3          # dB
            aperture            : 0.03       # m^2
            aperture_efficiency : 0.6
            polarization        : 'RHCP'
            pattern             : !include 3dB_pattern.yaml
            noise_temp          : 1000       # K
            tracking            : False
            pointing_loss       : 0          # dB
        cable :
            gain                : -0.75      # dB
            noise_figure        : 0.75       # dB
        lna :
            gain                : 35         # dB
            noise_figure        : 2.75       # dB
        filter :
            gain                : -3.5       # dB
            noise_figure        : 3.5        # dB
        demodulator :
            gain                : 0          # dB
            noise_figure        : 15         # dB
        receiver :
            implementation_loss : 2          # dB
    tx :
        antenna :
            #gain                : 3          # dB
            aperture            : 0.03       # m^2
            aperture_efficiency : 0.6
            polarization        : 'RHCP'
            pattern             : !include 3dB_pattern.yaml
            tracking            : False
            pointing_loss       : 0          # dB
        pa :
            power               : 1.5        # dBW


ground_station :
    rx :
        antenna :
            #gain                : 3          # dB
            aperture            : 0.03       # m^2
            aperture_efficiency : 0.6
            polarization        : 'RHCP'
            pattern             : 
            noise_temp          : 300        # K
            tracking            : True
            pointing_loss       : 0          # dB
        cable :
            gain                : -0.75      # dB
            noise_figure        : 0.75       # dB
        lna :
            gain                : 35         # dB
            noise_figure        : 2.75       # dB
        filter :
            gain                : -3.5       # dB
            noise_figure        : 3.5        # dB
        demodulator :
            gain                : 0          # dB
            noise_figure        : 15         # dB

    tx :
        antenna :
            #gain                : 3          # dB
            aperture            : 0.03       # m^2
            aperture_efficiency : 0.6
            polarization        : 'RHCP'
            pattern             : 
            tracking            : True
            pointing_loss       : 0          # dB
        pa :
            power               : 23        # dBW


downlink_channel :
    name                        : 'X-Band'
    bitrate                     : 1e6       # Hz
    allocation                  : 500e4     # Hz
    center_freq                 : 10000     # MHz
    atmospheric_loss            : 1         # dB
    ionospheric_loss            : 1         # dB
    rain_loss                   : 2         # dB
    multipath_fading            : 0         # dB
    polarization_mismatch_loss  : 3         # dB

uplink_channel :
    name                        : 'C-Band'
    bitrate                     : 500e3     # Hz
    allocation                  : 5e6       # Hz
    center_freq                 : 5000      # MHz
    atmospheric_loss            : 0.5       # dB
    ionospheric_loss            : 0.5       # dB
    rain_loss                   : 1         # dB
    multipath_fading            : 0         # dB
    polarization_mismatch_loss  : 3         # dB


geometry :
    apoapsis_altitude           : 35786     # km
    periapsis_altitude          : 35786     # km
    min_elevation               : 5         # degrees