###########################################################################
#
# Definition of a 65 cm TV dish based receiver
#
###########################################################################


# Define the nominal performance
nominal :
    rx :
        antenna :
            #gain                : 3          # dB
            aperture            : 0.33       # m^2
            aperture_efficiency : 0.6
            polarization        : 'RHCP'
            pattern             : 
            noise_temp          : 100        # K
            tracking            : True
            pointing_loss       : 0.5        # dB
        cable :
            gain                : -0.5       # dB
            noise_figure        : 0.5        # dB
        lna :
            gain                : 30         # dB
            noise_figure        : 1.0        # dB
        filter :
            gain                : -3.5       # dB
            noise_figure        : 3.5        # dB
        demodulator :
            gain                : 0          # dB
            noise_figure        : 5          # dB
        
    tx :
        antenna :
            #gain                : 3          # dB
            aperture            : 0.159      # m^2
            aperture_efficiency : 0.6
            polarization        : 'RHCP'
            pattern             : 
            tracking            : True
            pointing_loss       : 0          # dB
        pa :
            power               : 10         # dBW


# Define the statistical disctributions for Monte-Carlo analysis
statistical :
    rx :
        antenna :
            #gain :
            #  - 'Gaussian'
            #   - 0
            aperture :
                - 'Gaussian'
                - 0.01
            aperture_efficiency :
                - 'Gaussian'
                - 0.02
            polarization :
                - 'NotValid'
            pattern :
                - 'Gaussian'
                - 0
            noise_temp :
                - 'Gaussian'
                - 3.3
            tracking :
                - 'NotValid'
            pointing_loss :
                - 'Gaussian'
                - 0.2
        cable :
            gain :
                - 'Gaussian'
                - 0.05
            noise_figure :
                - 'Gaussian'
                - 0.05
        lna :
            gain :
                - 'Gaussian'
                - 0.15
            noise_figure :
                - 'Gaussian'
                - 0.1
        filter :
            gain :
                - 'Gaussian'
                - 0.1
            noise_figure :
                - 'Gaussian'
                - 0.1
        demodulator :
            gain :
                - 'Gaussian'
                - 0
            noise_figure :
                - 'Gaussian'
                - 0
        
    tx :
        antenna :
            #gain :
            #    - 'Gaussian'
            #    - 0
            aperture :
                - 'Gaussian'
                - 0
            aperture_efficiency :
                - 'Gaussian'
                - 0
            polarization :
                - 'NotValid'
            pattern :
                - 'Gaussian'
                - 0
            tracking :
                - 'NotValid'
            pointing_loss :
                - 'Gaussian'
                - 0
        pa :
            power :
                - 'Gaussian'
                - 0